"""
calculate_table_task_comp.py
=============================

Overview
--------
This script parses TinyVLA evaluation log files (.txt) generated by the
task composition evaluation pipeline (`run_libero_eval_task_comp.py`) and
aggregates their results into a structured, formatted Excel (.xlsx) table.

It supports two task composition difficulty levels:

  - **L1 (Compositional Generalization Level 1)**:
    The model must apply known manipulation primitives (pick-place, open drawer)
    to NEW object-target combinations never seen together during training.
    Example: trained on "plate → stove" and "bowl → cabinet", tested on
    "plate → cabinet" (novel object-target pair).

  - **L2 (Compositional Generalization Level 2)**:
    Multi-step chained tasks combining two sequential primitives. The model
    must execute longer-horizon behaviors not seen as a unit during training.
    Example: "Put the bowl on the stove AND turn on the stove".

Output Excel Format
-------------------
Each row corresponds to one task composition task. The 11 columns are:

  1.  # Task               — 1-based task index
  2.  Task Command         — the full task description tested
  3.  Reference Task       — training-time task(s) whose primitives are composed
  4.  SR% - Seed 0         — success rate for seed 0 (e.g., "84.0%")
  5.  Task Completion - S0 — N/50 completion for seed 0
  6.  SR% - Seed 1         — success rate for seed 1
  7.  Task Completion - S1 — N/50 completion for seed 1
  8.  SR% - Seed 2         — success rate for seed 2
  9.  Task Completion - S2 — N/50 completion for seed 2
  10. Mean SR% ± Std       — arithmetic mean ± sample std across seeds
  11. Mean Task Completion — average N/50 based on mean success rate

A final summary row reports per-seed means and the global mean ± std
computed from seed-level averages (standard VLA reporting convention).

Task Composition Levels — Fixed Task Lists
-------------------------------------------
L1 Tasks (5 tasks, all in libero_goal scene):
  1. Put the plate on the top of the cabinet
  2. Put the plate on the stove
  3. Put the cream cheese on the top of the cabinet
  4. Put the cream cheese on the plate
  5. Open the top layer of the drawer and put the cream cheese inside

L2 Tasks (5 tasks, chained operations):
  1. Open the middle layer of the drawer and put the bowl inside
  2. Put the bowl on the stove and turn on the stove
  3. Put the cream cheese on the bowl and put the bowl on the plate
  4. Push the plate to the front of the stove and put the bowl on the plate
  5. Put the cream cheese on the bowl and put the bowl on the top of the cabinet

Dependencies
------------
  - openpyxl     : Excel workbook creation and cell formatting
  - re           : Regular expression matching for log file parsing
  - math         : Standard deviation computation
  - glob         : File pattern expansion for auto-detect mode
  - argparse     : Command-line argument parsing
  - os           : Filesystem path utilities
  - collections  : defaultdict for multi-file aggregation

Usage
-----
Auto-detect mode (recommended):
    python calculate_table_task_comp.py --txt_dir /path/to/logs output.xlsx
    python calculate_table_task_comp.py --level l2 --txt_dir /path/to/logs output.xlsx

Manual mode (specify files per seed explicitly):
    python calculate_table_task_comp.py \\
        --manual \\
        --seed0 seed0.txt \\
        --seed1 seed1.txt \\
        --seed2 seed2.txt \\
        output.xlsx
"""

import re           # Regular expressions for extracting numeric values from log lines
import math         # Used for computing sample standard deviation (math.sqrt)
import argparse     # Command-line interface argument parsing
import os           # OS-level path operations (basename, join, makedirs)
import glob         # Unix-style wildcard file path expansion
from collections import defaultdict  # Dictionary with automatic default value factory
from openpyxl import Workbook        # Creates and manages Excel workbook objects
from openpyxl.styles import Font, Alignment  # Cell formatting: bold text, alignment


# =========================
# TASK ORDER & MAPPING
# =========================


def normalize_task_key(task_name):
    """
    Normalize a task description string into a canonical lowercase key.

    This function enables robust, case-insensitive matching between task
    descriptions as they appear in log files (which may vary in capitalization
    or have extra whitespace) and the hardcoded task names in the reference
    dictionaries.

    The normalization pipeline:
      1. Strip leading and trailing whitespace from the input string.
      2. Convert the entire string to lowercase.
      3. Collapse all internal whitespace sequences to a single space.

    Parameters
    ----------
    task_name : str
        The raw task description string to normalize. May contain mixed case,
        leading/trailing spaces, or irregular internal spacing.

    Returns
    -------
    str
        A normalized lowercase string with a single space between words.

    Examples
    --------
    >>> normalize_task_key("  Put The Bowl On The Stove  ")
    'put the bowl on the stove'
    >>> normalize_task_key("put  the  bowl  on  the  stove")
    'put the bowl on the stove'
    """
    return " ".join(task_name.strip().lower().split())


def get_task_comp_l1_order():
    """
    Return the fixed ordered list of 5 Level-1 task composition task descriptions.

    These five tasks represent compositional generalization at Level 1:
    the model is evaluated on object-target combinations that combine individually
    known object types and target locations but were never seen together in training.

    The order is used to control the row sequence in the generated Excel table,
    ensuring consistent layout regardless of how tasks appear in log files.

    Composition rationale for each task:
      1. Put the plate on the top of the cabinet
         → Training: plate manipulation + bowl→cabinet; novel: plate→cabinet
      2. Put the plate on the stove
         → Training: plate push + bowl→stove; novel: pick-place plate→stove
      3. Put the cream cheese on the top of the cabinet
         → Training: cream cheese→bowl + bowl→cabinet; novel: cream cheese→cabinet
      4. Put the cream cheese on the plate
         → Training: cream cheese→bowl + bowl→plate; novel: cream cheese→plate
      5. Open the top layer of the drawer and put the cream cheese inside
         → Training: open drawer + bowl inside; novel: cream cheese inside (same primitive)

    Returns
    -------
    list of str
        Five canonical L1 task description strings in their fixed display order.
    """
    return [
        "Put the plate on the top of the cabinet",
        "Put the plate on the stove",
        "Put the cream cheese on the top of the cabinet",
        "Put the cream cheese on the plate",
        "Open the top layer of the drawer and put the cream cheese inside",
    ]


def get_task_comp_l2_order():
    """
    Return the fixed ordered list of 5 Level-2 task composition task descriptions.

    These five tasks represent compositional generalization at Level 2:
    multi-step chained behaviors where two sequential primitives (each known
    independently) must be executed together in a novel combined sequence.

    The order is used to control the row sequence in the generated Excel table.

    Composition rationale for each task:
      1. Open the middle layer of the drawer and put the bowl inside
         → Training: open middle drawer + open top drawer and put bowl inside
      2. Put the bowl on the stove and turn on the stove
         → Training: put bowl on stove + turn on stove (novel chain)
      3. Put the cream cheese on the bowl and put the bowl on the plate
         → Training: cream cheese→bowl + bowl→plate (two pick-place in sequence)
      4. Push the plate to the front of the stove and put the bowl on the plate
         → Training: push plate + put bowl on plate (push + pick-place chain)
      5. Put the cream cheese on the bowl and put the bowl on the top of the cabinet
         → Training: cream cheese→bowl + bowl→cabinet (two sequential pick-place)

    Returns
    -------
    list of str
        Five canonical L2 task description strings in their fixed display order.
    """
    return [
        "Open the middle layer of the drawer and put the bowl inside",
        "Put the bowl on the stove and turn on the stove",
        "Put the cream cheese on the bowl and put the bowl on the plate",
        "Push the plate to the front of the stove and put the bowl on the plate",
        "Put the cream cheese on the bowl and put the bowl on the top of the cabinet",
    ]


def get_reference_mapping(level="l1"):
    """
    Build and return a mapping from each task composition task to its training
    reference task(s), whose primitives are recombined in the evaluated task.

    Each entry explains the compositional lineage: which training tasks
    the model must generalize from to successfully complete the new task.
    This mapping is displayed in the "Reference Task" column of the Excel table,
    providing interpretability for each evaluation result.

    All dictionary keys are normalized to lowercase via `normalize_task_key`
    to enable case-insensitive lookup when matching against log file strings.

    Parameters
    ----------
    level : str, optional
        Composition level to retrieve the mapping for.
        Must be "l1" (default) or "l2".

    Returns
    -------
    dict
        Mapping from normalized task description string (str) → reference task
        string (str). For L2 tasks, the reference is a " / "-separated pair
        of training task names. For L1 tasks, it is a single training task.

    Notes
    -----
    L1 Reference Interpretation:
      Each L1 composition task reuses one primitive (action type) from training
      but applies it to a novel object or target. The reference task is the
      closest training task that shares the key manipulation primitive.

    L2 Reference Interpretation:
      Each L2 composition task chains two distinct primitives. Both source
      training tasks are listed, separated by " / ", to show which behaviors
      need to be combined.

    Examples
    --------
    >>> mapping = get_reference_mapping("l1")
    >>> mapping[normalize_task_key("Put the plate on the stove")]
    'Put the bowl on the stove'
    >>> mapping = get_reference_mapping("l2")
    >>> mapping[normalize_task_key("Put the bowl on the stove and turn on the stove")]
    'Put the bowl on the stove  /  Turn on the stove'
    """
    if level == "l2":
        # L2: each task combines two chained training primitives
        return {
            normalize_task_key("Open the middle layer of the drawer and put the bowl inside"):
                # Chain: open middle drawer (novel drawer layer) + put bowl inside (known)
                "Open the middle drawer of the cabinet  /  Open the top drawer and put the bowl inside",

            normalize_task_key("Put the bowl on the stove and turn on the stove"):
                # Chain: pick-place bowl → stove (known) + turn on stove (known)
                "Put the bowl on the stove  /  Turn on the stove",

            normalize_task_key("Put the cream cheese on the bowl and put the bowl on the plate"):
                # Chain: cream cheese → bowl (known) + bowl → plate (known)
                "Put the cream cheese in the bowl  /  Put the bowl on the plate",

            normalize_task_key("Push the plate to the front of the stove and put the bowl on the plate"):
                # Chain: push plate → stove front (known) + put bowl on plate (known)
                "Push the plate to the front of the stove  /  Put the bowl on the plate",

            normalize_task_key("Put the cream cheese on the bowl and put the bowl on the top of the cabinet"):
                # Chain: cream cheese → bowl (known) + bowl → cabinet top (known)
                "Put the cream cheese in the bowl  /  Put the bowl on the top of the cabinet",
        }

    # L1: each task applies a known primitive to a novel object-target combination
    return {
        normalize_task_key("Put the plate on the top of the cabinet"):
            # Training: bowl → cabinet; novel: plate replaces bowl
            "Put the bowl on the top of the cabinet",

        normalize_task_key("Put the plate on the stove"):
            # Training: bowl → stove; novel: plate replaces bowl
            "Put the bowl on the stove",

        normalize_task_key("Put the cream cheese on the top of the cabinet"):
            # Training: wine bottle → cabinet; novel: cream cheese replaces wine bottle
            "Put the wine bottle on the top of the cabinet",

        normalize_task_key("Put the cream cheese on the plate"):
            # Training: cream cheese → bowl; novel: plate replaces bowl as target
            "Put the cream cheese on the bowl",

        normalize_task_key("Open the top layer of the drawer and put the cream cheese inside"):
            # Training: open drawer + bowl inside; novel: cream cheese replaces bowl
            "Open the top layer of the drawer and put the bowl inside",
    }


# =========================
# PARSING
# =========================


def parse_txt_file(filepath):
    """
    Parse a single TinyVLA task composition evaluation log file.

    Extracts per-task success rates and episode counts by scanning the log
    for structured marker lines. Supports two log format variants:
      - **TinyVLA format**: uses "Command:" and "# episodes:" markers
      - **OpenVLA format**: uses "# episodes completed:" instead

    Expected log structure for each task block:
    ::

        COMMAND: Put the plate on the stove
        ...
        # episodes: 50               ← TinyVLA format
        # episodes completed: 50     ← OpenVLA format (alternative)
        ...
        Task success rate: 0.8400    ← decimal value; terminates the block

    Parameters
    ----------
    filepath : str
        Absolute or relative path to the `.txt` log file to parse.

    Returns
    -------
    rates : dict
        Mapping from normalized lowercase task key (str) → success rate in
        percent (float). Example: {"put the plate on the stove": 84.0}
    episodes : dict
        Mapping from normalized lowercase task key (str) → number of episodes
        run (int). Defaults to 50 if the episode count line was not found.
    task_order : list of str
        Task description strings in their original capitalization, in the order
        they first appear in the log file. Used for display in the Excel table.

    Notes
    -----
    - Duplicate task entries (same task appearing multiple times in one file)
      are silently skipped; only the first occurrence is stored.
    - The "# episodes completed:" variant check uses `"completed" not in line_s`
      to distinguish it from the simpler "# episodes:" pattern, preventing
      double-counting when only one format is present.
    - Success rates are read as decimals (0.8400) and converted to percentages
      (84.0) for uniform representation across the rest of the pipeline.
    - `normalize_task_key` is applied to all task keys for robust matching.
    """
    rates = {}          # normalized_key → success rate (%)
    episodes = {}       # normalized_key → episode count
    task_order = []     # original-case task descriptions in encounter order

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    current_task = None         # Original-case task description of the current block
    current_task_lower = None   # Normalized lowercase key of the current block
    current_episodes = None     # Episode count for the current task block

    for line in lines:
        line_s = line.strip()  # Remove leading/trailing whitespace and newline

        # ── Detect task command marker ─────────────────────────────────────
        # "Command: <task_description>" marks the start of a new task block.
        # `split("Command:", 1)` limits to one split to handle colons in the description.
        if line_s.startswith("Command:"):
            current_task = line_s.split("Command:", 1)[-1].strip()
            current_task_lower = normalize_task_key(current_task)  # Normalize for dict key

        # ── Extract OpenVLA-style episode count ────────────────────────────
        # "# episodes completed: N" — used by OpenVLA evaluation logs
        if current_task and "# episodes completed:" in line_s:
            m = re.search(r"# episodes completed:\s*(\d+)", line_s)
            if m:
                current_episodes = int(m.group(1))  # Convert matched string to integer

        # ── Extract TinyVLA-style episode count ───────────────────────────
        # "# episodes: N" — used by TinyVLA evaluation logs
        # The `"completed" not in line_s` guard prevents matching
        # "# episodes completed:" again in case both lines appear.
        if current_task and "# episodes:" in line_s and "completed" not in line_s:
            m = re.search(r"# episodes:\s*(\d+)", line_s)
            if m:
                current_episodes = int(m.group(1))

        # ── Extract success rate and finalize task block ───────────────────
        # "Task success rate: X.XXXX" marks the end of the current task block.
        if current_task and "Task success rate:" in line_s:
            m = re.search(r"Task success rate:\s*([\d.]+)", line_s)
            if m:
                rate_pct = float(m.group(1)) * 100  # Convert decimal → percentage

                if current_task_lower not in rates:  # Skip if task was already recorded
                    rates[current_task_lower] = rate_pct
                    episodes[current_task_lower] = current_episodes if current_episodes else 50
                    task_order.append(current_task)  # Preserve original capitalization for display

                # Reset parser state: ready for the next task block
                current_task = None
                current_task_lower = None
                current_episodes = None

    return rates, episodes, task_order


def merge_txt_files(txt_files_list):
    """
    Merge multiple TinyVLA log files belonging to the same random seed.

    When a single evaluation run is split across multiple log files (e.g.,
    tasks 1-3 in one job and tasks 4-5 in another), this function aggregates
    all results. If the same task appears in multiple files, its success rates
    are averaged (arithmetic mean over the number of occurrences).

    Parameters
    ----------
    txt_files_list : list of str
        File paths to `.txt` log files for a single seed. One or more files.

    Returns
    -------
    merged_rates : dict
        Mapping from normalized task key (str) → averaged success rate in %
        (float). Example: {"put the plate on the stove": 84.0}
    task_episodes : dict
        Mapping from normalized task key (str) → episode count (int).
        Taken from the last file that reported this task (always 50 in practice).
    all_tasks : list of str
        Original-case task descriptions in the order first encountered across
        all files. Used for ordering in the Excel table.

    Notes
    -----
    - `defaultdict(list)` allows appending multiple success rate values for
      the same task key without initialization checks.
    - The arithmetic mean across files corrects for any task that was run
      partially across multiple jobs, ensuring a single representative rate.
    - Episode count uses the last value seen (via `eps.get(tk, 50)`) since
      all evaluations use exactly 50 episodes per task.
    """
    task_rates_list = defaultdict(list)  # normalized_key → list of rates from each file
    task_episodes = {}    # normalized_key → episode count
    all_tasks = []        # Original-case task descriptions in encounter order

    for fp in txt_files_list:
        rates, eps, order = parse_txt_file(fp)  # Parse one file

        for task in order:
            tk = normalize_task_key(task)  # Use normalized key as the dict key

            if tk not in task_rates_list:
                all_tasks.append(task)  # Record original-case name on first encounter

            task_rates_list[tk].append(rates[tk])  # Accumulate this file's rate
            task_episodes[tk] = eps.get(tk, 50)    # Update episode count (always 50)

    # Compute the arithmetic mean of all accumulated rates per task key
    merged_rates = {tk: sum(v) / len(v) for tk, v in task_rates_list.items()}

    return merged_rates, task_episodes, all_tasks


# =========================
# EXCEL GENERATION
# =========================


def write_excel(output_xlsx, txt_files_by_seed, level="l1"):
    """
    Parse all seed log files, aggregate results, and write the formatted Excel table.

    Orchestrates the full reporting pipeline for task composition evaluation:
      1. Parse and merge log files for each of the 3 seeds.
      2. Look up the reference training task for each composition task.
      3. Iterate over the fixed task order (L1 or L2).
      4. For each task and seed: extract rate, compute N/50 completion.
      5. Compute per-task mean ± sample standard deviation across seeds.
      6. Append a final summary row with per-seed and global mean ± std.
      7. Apply bold formatting to header and summary rows.
      8. Auto-fit column widths and save the workbook.

    Parameters
    ----------
    output_xlsx : str
        Output file path for the generated Excel workbook (e.g., "results.xlsx").
    txt_files_by_seed : dict
        Dictionary mapping seed index (int: 0, 1, 2) → list of file path strings.
        Example:
          {
            0: ["logs/seed0_part1.txt"],
            1: ["logs/seed1.txt"],
            2: ["logs/seed2_part1.txt", "logs/seed2_part2.txt"]
          }
    level : str, optional
        Composition level: "l1" (default) for object-target generalization,
        or "l2" for multi-step chained task generalization.

    Returns
    -------
    None
        Writes the Excel file to `output_xlsx` and prints status messages.

    Notes
    -----
    NaN Handling:
    ─────────────
    If a task is missing from a seed's data, its rate is float('nan') and
    its completion defaults to "0/50". NaN values are excluded from mean/std
    computation via the `r == r` identity (NaN is not equal to itself in
    IEEE 754 arithmetic). Only non-NaN rates are accumulated in `all_seed_rates`.

    Per-Task Mean ± Std:
    ─────────────────────
    Uses the **sample standard deviation** (divides by N-1), appropriate
    for the small sample size of 3 seeds. If only one valid rate is available,
    the std is reported as 0.0.

    Global Mean ± Std (Standard VLA Convention):
    ─────────────────────────────────────────────
    The global std is computed across the per-seed means (not across all
    task×seed combinations):
      seed_mean_k = mean(all task rates for seed k)
      global_mean = mean(seed_mean_0, seed_mean_1, seed_mean_2)
      global_std  = sample_std(seed_mean_0, seed_mean_1, seed_mean_2)

    This matches the reporting convention used in VLA benchmark papers.
    """
    # ── Step 1: Parse and merge log files for each seed ────────────────────
    all_rates = []      # List of 3 dicts: all_rates[seed_idx][tk] = rate (%)
    all_episodes = []   # List of 3 dicts: all_episodes[seed_idx][tk] = episode count

    for seed_idx in range(3):
        fps = txt_files_by_seed[seed_idx]
        print(f"  Seed {seed_idx}: {len(fps)} file")
        for fp in fps:
            print(f"    - {os.path.basename(fp)}")  # Show filename only for clarity

        # Merge all files for this seed into a single rates dict
        rates, eps, _ = merge_txt_files(fps)
        all_rates.append(rates)
        all_episodes.append(eps)
        print(f"    -> {len(rates)} task trovati")

    # ── Step 2: Load reference mapping and fixed task order ────────────────
    ref_mapping = get_reference_mapping(level)    # Composition task → training reference
    fixed_order = (
        get_task_comp_l2_order() if level == "l2" else get_task_comp_l1_order()
    )  # Canonical task list for row ordering

    # ── Step 3: Create Excel workbook and worksheet ────────────────────────
    wb = Workbook()
    ws = wb.active
    ws.title = f"Task Comp {level.upper()}"  # Name the worksheet (e.g., "Task Comp L1")

    # ── Step 4: Write and format the header row ────────────────────────────
    headers = [
        "# Task",
        "Task Command",
        "Reference Task",
        "SR% - Seed 0", "Task Completion - Seed 0",
        "SR% - Seed 1", "Task Completion - Seed 1",
        "SR% - Seed 2", "Task Completion - Seed 2",
        "Mean SR% ± Std",
        "Mean Task Completion",
    ]
    ws.append(headers)

    # Apply bold font and center-aligned text wrapping to all header cells
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="center", wrap_text=True)

    # ── Step 5: Initialize accumulators for the final summary row ──────────
    # all_seed_rates[k]       : list of per-task success rates for seed k (NaN excluded)
    # all_seed_completions[k] : list of (success_count, episode_count) tuples for seed k
    all_seed_rates = [[], [], []]
    all_seed_completions = [[], [], []]

    # ── Step 6: Process each task in canonical fixed order ─────────────────
    for task_idx, task_cmd in enumerate(fixed_order, start=1):
        # Normalize the canonical task name for dictionary lookups
        tk = normalize_task_key(task_cmd)

        # Look up the training reference task(s) for this composition task
        ref_task = ref_mapping.get(tk, "")  # Empty string if no mapping found

        seed_rates = []         # Success rates (%) for this task, one per seed
        seed_completions = []   # "N/M" completion strings, one per seed

        # ── Extract per-seed data for this task ────────────────────────────
        for seed_idx in range(3):
            # Retrieve rate; float('nan') if this task is absent from this seed's data
            rate = all_rates[seed_idx].get(tk, float("nan"))
            episodes = all_episodes[seed_idx].get(tk, 50)  # Default to 50 episodes

            # Compute integer success count: only if rate is a valid number (not NaN)
            # NaN check: `rate == rate` is False for NaN (IEEE 754 property)
            succ = int(round(rate / 100 * episodes)) if rate == rate else 0

            seed_rates.append(rate)
            seed_completions.append(f"{succ}/{episodes}")

            # Accumulate only valid (non-NaN) rates for the summary row
            if rate == rate:  # True only when rate is not NaN
                all_seed_rates[seed_idx].append(rate)
                all_seed_completions[seed_idx].append((succ, episodes))

        # ── Compute per-task mean ± sample std across seeds ────────────────
        # Filter out NaN values before computing statistics
        valid = [r for r in seed_rates if r == r]

        if valid:
            mean_r = sum(valid) / len(valid)  # Arithmetic mean of valid rates

            # Sample standard deviation (N-1 denominator); 0.0 if only one valid rate
            std_r = (
                math.sqrt(sum((r - mean_r) ** 2 for r in valid) / (len(valid) - 1))
                if len(valid) > 1 else 0.0
            )
            mean_display = f"{mean_r:.1f}% ± {std_r:.1f}%"

            # Average episode count across seeds (should always be 50)
            avg_episodes = int(round(
                sum(all_episodes[seed_idx].get(tk, 50) for seed_idx in range(3)) / 3
            ))
            # Mean task completion: average successes per seed out of avg_episodes
            avg_succ = int(round(mean_r / 100 * avg_episodes))
        else:
            # No valid data for this task across any seed
            mean_display = "N/A"
            avg_episodes = 50
            avg_succ = 0

        # ── Append data row to the worksheet ──────────────────────────────
        ws.append([
            task_idx,            # Column 1: 1-based task index
            task_cmd,            # Column 2: canonical task description (original case)
            ref_task,            # Column 3: training reference task(s)
            # Columns 4-5: Seed 0 success rate and completion
            f"{seed_rates[0]:.1f}%" if seed_rates[0] == seed_rates[0] else "N/A",
            seed_completions[0],
            # Columns 6-7: Seed 1
            f"{seed_rates[1]:.1f}%" if seed_rates[1] == seed_rates[1] else "N/A",
            seed_completions[1],
            # Columns 8-9: Seed 2
            f"{seed_rates[2]:.1f}%" if seed_rates[2] == seed_rates[2] else "N/A",
            seed_completions[2],
            mean_display,                    # Column 10: mean ± std across seeds
            f"{avg_succ}/{avg_episodes}",    # Column 11: mean task completion as N/50
        ])

    # ── Step 7: Build and append the final summary row ─────────────────────
    # This row aggregates performance across all tasks, per seed and globally.
    final_row = ["", "Mean% ± Std%", ""]  # Columns 1-3: index (blank), label, reference (blank)

    # Per-seed aggregate statistics
    for seed_idx in range(3):
        rates = all_seed_rates[seed_idx]  # All valid task rates for this seed

        if rates:
            m = sum(rates) / len(rates)  # Mean success rate across all tasks for this seed

            # Sample std across all task rates for this seed
            s = (
                math.sqrt(sum((r - m) ** 2 for r in rates) / (len(rates) - 1))
                if len(rates) > 1 else 0.0
            )

            # Aggregate completion: total successes and total episodes across all tasks
            ts = sum(c[0] for c in all_seed_completions[seed_idx])  # Total successes
            te = sum(c[1] for c in all_seed_completions[seed_idx])  # Total episodes

            final_row.append(f"{m:.2f}% ± {s:.2f}%")  # "XX.XX% ± YY.YY%"
            final_row.append(f"{ts}/{te}")               # "N/M"
        else:
            final_row.extend(["N/A", "0/0"])  # No data for this seed

    # ── Global mean ± std (standard VLA reporting convention) ─────────────
    # Compute the mean of each seed's mean, then the std across those seed means.
    seed_means = []
    for seed_idx in range(3):
        if all_seed_rates[seed_idx]:
            # Per-seed mean: average success rate across all tasks for seed k
            seed_means.append(
                sum(all_seed_rates[seed_idx]) / len(all_seed_rates[seed_idx])
            )

    if seed_means:
        gm = sum(seed_means) / len(seed_means)  # Global mean (mean of seed means)

        # Sample std across seed means (3 values: one per seed)
        gs = (
            math.sqrt(sum((m - gm) ** 2 for m in seed_means) / (len(seed_means) - 1))
            if len(seed_means) > 1 else 0.0
        )

        # Global completion totals: sum all successes and episodes across all seeds
        gt_s = sum(sum(c[0] for c in all_seed_completions[i]) for i in range(3))
        gt_e = sum(sum(c[1] for c in all_seed_completions[i]) for i in range(3))

        final_row.append(f"{gm:.2f}% ± {gs:.2f}%")  # Global "XX.XX% ± YY.YY%"
        final_row.append(f"{gt_s}/{gt_e}")             # Global "N/M"
    else:
        final_row.extend(["N/A", "0/0"])

    ws.append(final_row)  # Append the completed summary row to the worksheet

    # Apply bold formatting to the final summary row for visual emphasis
    for cell in ws[ws.max_row]:
        cell.font = Font(bold=True)

    # ── Step 8: Auto-fit column widths ────────────────────────────────────
    for col in ws.columns:
        letter = col[0].column_letter  # Get the Excel column letter (A, B, C, ...)

        # Find the length of the longest string value in this column
        max_len = max(
            (len(str(c.value or "")) for c in col),
            default=0  # Default to 0 if the column is empty
        )

        # Set column width: content length + 2 padding, capped at 65 to prevent excessive width
        ws.column_dimensions[letter].width = min(max_len + 2, 65)

    # ── Step 9: Save the workbook to disk ─────────────────────────────────
    wb.save(output_xlsx)
    print(f"\n[OK] Excel salvato: {output_xlsx}")


# =========================
# AUTO-DETECT
# =========================


def find_txt_files_by_seed(base_dir, pattern_prefix=None, level="l1"):
    """
    Automatically discover TinyVLA task composition log files organized by seed.

    Searches `base_dir` for `.txt` files matching the naming convention used by
    the TinyVLA task composition evaluation pipeline:
        {pattern_prefix}*seed_{seed_idx}*.txt

    A fallback pattern without the underscore before the seed number is also
    tried if the primary pattern yields no results:
        {pattern_prefix}*seed{seed_idx}*.txt

    This handles both `seed_0` and `seed0` naming variants that may appear
    depending on the evaluation script version used.

    Parameters
    ----------
    base_dir : str
        Directory path in which to search for log files.
    pattern_prefix : str or None, optional
        Filename prefix shared by all log files. If None, defaults to
        "EVAL-task_comp_{level}" (e.g., "EVAL-task_comp_l1"). This matches
        the naming convention of `run_libero_eval_task_comp.py` outputs.
    level : str, optional
        Composition level ("l1" or "l2"). Used to construct the default
        `pattern_prefix` when none is explicitly provided. Default: "l1".

    Returns
    -------
    dict or None
        Dictionary mapping seed index (int: 0, 1, 2) → sorted list of matching
        file path strings. Returns None if any seed has zero matching files,
        allowing the caller to handle the error before proceeding.

    Notes
    -----
    - Files within each seed are sorted alphabetically, which typically
      corresponds to the task group order for split evaluation jobs.
    - The two-step pattern matching (primary with underscore, fallback without)
      ensures compatibility across different evaluation script versions.
    - Returning None (rather than raising an exception) allows `main()` to
      print a user-friendly error message and exit cleanly.

    Example
    -------
    >>> files = find_txt_files_by_seed("/logs", level="l1")
    >>> files[0]
    ['/logs/EVAL-task_comp_l1-2025-06-01--seed_0--part1.txt']
    """
    # Set the default pattern prefix based on the composition level
    if pattern_prefix is None:
        pattern_prefix = f"EVAL-task_comp_{level}"  # e.g., "EVAL-task_comp_l1"

    txt_files_by_seed = {0: [], 1: [], 2: []}  # Initialize empty file lists per seed

    print(f"\n[INFO] Cercando in: {base_dir}")

    for seed_idx in range(3):
        # Primary pattern: "seed_N" with underscore separator (newer naming convention)
        pattern = os.path.join(base_dir, f"{pattern_prefix}*seed_{seed_idx}*.txt")
        matches = sorted(glob.glob(pattern))  # Sorted for deterministic ordering

        # Fallback pattern: "seedN" without underscore (older naming convention)
        if not matches:
            pattern = os.path.join(base_dir, f"{pattern_prefix}*seed{seed_idx}*.txt")
            matches = sorted(glob.glob(pattern))

        txt_files_by_seed[seed_idx] = matches

        if matches:
            print(f"  Seed {seed_idx}: {len(matches)} file")
            for m in matches:
                print(f"    - {os.path.basename(m)}")  # Display only filename for readability
        else:
            # Critical failure: missing files for this seed cannot be recovered
            print(f"  Seed {seed_idx}: NESSUN FILE!")
            return None  # Signal failure to the caller

    return txt_files_by_seed


# =========================
# MAIN
# =========================


def main():
    """
    Command-line entry point for the TinyVLA Task Composition Excel table generator.

    Parses CLI arguments to determine the composition level, file discovery mode,
    and output path. Then calls `write_excel()` to produce the final `.xlsx` report.

    Two mutually exclusive operating modes are supported:

    **Auto-detect mode** (``--txt_dir``):
      Scans the given directory for `.txt` files matching the pattern
      ``{--pattern}*seed_{0,1,2}*.txt`` (with underscore fallback).
      The default pattern is automatically constructed from ``--level``.
      This is the recommended mode for standard evaluation workflows.

    **Manual mode** (``--manual``):
      The user provides explicit file lists for each seed via ``--seed0``,
      ``--seed1``, and ``--seed2``. Useful when files do not follow the
      standard naming convention or are in different directories.

    CLI Arguments
    -------------
    Mutually exclusive group (exactly one required):
      --txt_dir PATH
          Directory containing all `.txt` log files (auto-detect mode).
      --manual
          Enable manual file specification mode.

    Optional:
      --level {l1, l2}
          Task composition level to process. Default: "l1".
      --pattern PREFIX
          Custom filename prefix for auto-detect (overrides the default
          "EVAL-task_comp_{level}" pattern).
      --seed0 FILE [FILE ...]
          One or more log file paths for seed 0 (manual mode only).
      --seed1 FILE [FILE ...]
          One or more log file paths for seed 1 (manual mode only).
      --seed2 FILE [FILE ...]
          One or more log file paths for seed 2 (manual mode only).

    Positional (required):
      output_xlsx
          Output path for the generated Excel file (e.g., "results/l1.xlsx").

    Exit Codes
    ----------
    0 : Success — Excel file written successfully.
    1 : Error — manual mode used without all three --seedN arguments, or
        auto-detect failed to find files for all seeds.

    Examples
    --------
    Auto-detect L1:
        python calculate_table_task_comp.py \\
            --level l1 --txt_dir /mnt/logs results_l1.xlsx

    Auto-detect L2 with custom pattern:
        python calculate_table_task_comp.py \\
            --level l2 --txt_dir /mnt/logs \\
            --pattern MY-EVAL-task_comp_l2 results_l2.xlsx

    Manual mode:
        python calculate_table_task_comp.py \\
            --manual \\
            --seed0 logs/seed0.txt \\
            --seed1 logs/seed1.txt \\
            --seed2 logs/seed2.txt \\
            results.xlsx
    """
    parser = argparse.ArgumentParser(
        description="Genera tabella Excel Task Composition L1/L2 (TinyVLA) da file log .txt"
    )

    # Mutually exclusive group: only one input mode may be selected
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--txt_dir",
        help="Directory con i file .txt (auto-detect)"
    )
    group.add_argument(
        "--manual",
        action="store_true",  # Boolean flag: True if --manual is present
        help="Specifica file manualmente"
    )

    parser.add_argument(
        "--level",
        default="l1",
        choices=["l1", "l2"],  # Only these two values are valid
        help="Livello di composizione: l1 (default) o l2"
    )
    parser.add_argument(
        "--pattern",
        default=None,  # None triggers automatic default construction in find_txt_files_by_seed
        help="Prefix per auto-detect (default: EVAL-task_comp_<level>)"
    )
    parser.add_argument(
        "--seed0",
        nargs="+",  # Accepts one or more values
        help="File per seed 0 (modo manuale)"
    )
    parser.add_argument(
        "--seed1",
        nargs="+",
        help="File per seed 1 (modo manuale)"
    )
    parser.add_argument(
        "--seed2",
        nargs="+",
        help="File per seed 2 (modo manuale)"
    )
    parser.add_argument(
        "output_xlsx",
        help="File Excel di output"
    )

    args = parser.parse_args()

    # Print ASCII banner to identify the script and current level
    print("\n" + "=" * 60)
    print(f"  TASK COMPOSITION {args.level.upper()} (TinyVLA) - EXCEL TABLE GENERATOR")
    print("=" * 60)

    # ── Determine the seed-to-file mapping based on the chosen mode ────────
    if args.manual:
        # Manual mode: validate that all three seed file lists were provided
        if not (args.seed0 and args.seed1 and args.seed2):
            print("[ERROR] --manual richiede --seed0, --seed1, --seed2")
            exit(1)  # Exit with error code 1

        # Build the mapping from explicitly provided file lists
        txt_files_by_seed = {
            0: args.seed0,   # List of file paths for seed 0
            1: args.seed1,   # List of file paths for seed 1
            2: args.seed2    # List of file paths for seed 2
        }
    else:
        # Auto-detect mode: scan the directory for matching files
        txt_files_by_seed = find_txt_files_by_seed(
            args.txt_dir,
            args.pattern,  # None triggers default pattern construction
            args.level
        )
        if txt_files_by_seed is None:
            # find_txt_files_by_seed returns None if any seed has no files
            print("[ERROR] File non trovati per tutti i seed!")
            exit(1)

    # ── Generate the Excel table ───────────────────────────────────────────
    write_excel(args.output_xlsx, txt_files_by_seed, level=args.level)

    # Print completion banner
    print("=" * 60)
    print("  COMPLETATO!")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()  # Execute main() only when run as a script (not when imported as a module)