"""
generate_excel_comparison.py
=============================

Overview
--------
This script parses TinyVLA evaluation log files (.txt) generated by LIBERO
benchmark evaluation runs and aggregates their results into a formatted Excel
(.xlsx) comparison table.

It supports:
  - Evaluation results across **3 random seeds** (seed 0, 1, 2)
  - **Multiple log files per seed** (e.g., when tasks are split across jobs)
  - Both **default** task commands and **linguistic variation** commands
    (L1: paraphrase, L2: passive/descriptive, L3: referential/indirect)
  - **Case-insensitive matching** of task descriptions via a comprehensive mapping
  - **Automatic file discovery** from a directory (auto-detect mode) or
    **manual file specification** via CLI arguments

Output Excel Format
-------------------
The generated Excel table has 10 columns:
  1.  Original Task Command          — canonical task name
  2.  Variation Task Command         — actual command found in log files
  3.  Success Rate (%) - Seed 0      — formatted as "XX.X%"
  4.  Task Completion - Seed 0       — formatted as "N/50"
  5.  Success Rate (%) - Seed 1
  6.  Task Completion - Seed 1
  7.  Success Rate (%) - Seed 2
  8.  Task Completion - Seed 2
  9.  Mean Success Rate (%) ± Std    — mean and sample std across seeds
  10. Mean Task Completion            — average successes over 50 episodes

A final summary row reports the mean ± std success rate across all tasks
for each seed, and the global mean ± std computed from seed-level averages
(following the standard VLA evaluation reporting convention).

Linguistic Variation Levels
----------------------------
  DEFAULT : Original full task command used during training
  L1      : Lexical paraphrase (synonymous verb/preposition swap)
  L2      : Passive or descriptive rephrasing (syntactic change)
  L3      : Referential expression (object identified indirectly)

Usage
-----
Auto-detect mode (finds files by naming pattern):
    python generate_excel_comparison.py \\
        --txt_dir /path/to/logs \\
        --pattern EVAL-libero_goal-tiny_vla \\
        output.xlsx

Manual mode (explicitly specify files per seed):
    python generate_excel_comparison.py \\
        --manual \\
        --seed0 seed0_part1.txt seed0_part2.txt \\
        --seed1 seed1.txt \\
        --seed2 seed2.txt \\
        output.xlsx

Dependencies
------------
  - openpyxl   : Excel file creation and formatting
  - re         : Regular expression parsing of log file lines
  - math       : Standard deviation computation
  - glob       : File pattern matching for auto-detect
  - argparse   : Command-line argument parsing
  - os         : Filesystem path utilities
  - collections: defaultdict for multi-file aggregation
"""

import re           # Regular expressions for parsing task success rates and episode counts
import math         # Used for computing sample standard deviation (math.sqrt)
import argparse     # Command-line interface argument parsing
from openpyxl import Workbook                          # Creates new Excel workbooks
from openpyxl.styles import Font, Alignment            # Cell formatting: bold, text alignment
import os                                              # OS-level path operations
import glob                                            # Unix-style pathname pattern expansion
from collections import defaultdict                    # Dict subclass with default factory


# =========================
# MAPPING COMPLETO DELLE VARIAZIONI
# =========================


def get_task_order():
    """
    Return the canonical ordered list of the 10 LIBERO-goal task names.

    This fixed ordering is used to control the row sequence in the output Excel
    table, ensuring consistent layout regardless of the order in which tasks
    appear in the log files.

    The tasks correspond to the 10 manipulation tasks in the libero_goal suite:
      1.  Open the middle layer of the drawer
      2.  Put the bowl on the stove
      3.  Put the wine bottle on the top of the drawer
      4.  Open the top layer of the drawer and put the bowl inside
      5.  Put the bowl on the top of the drawer
      6.  Push the plate to the front of the stove
      7.  Put the cream cheese in the bowl
      8.  Turn on the stove
      9.  Put the bowl on the plate
      10. Put the wine bottle on the rack

    Returns
    -------
    list of str
        The 10 canonical task description strings in their fixed display order.
    """
    return [
        "Open the middle layer of the drawer",
        "Put the bowl on the stove",
        "Put the wine bottle on the top of the drawer",
        "Open the top layer of the drawer and put the bowl inside",
        "Put the bowl on the top of the drawer",
        "Push the plate to the front of the stove",
        "Put the cream cheese in the bowl",
        "Turn on the stove",
        "Put the bowl on the plate",
        "Put the wine bottle on the rack"
    ]


def get_variation_mapping():
    """
    Build and return the complete case-insensitive mapping from every known
    task command variation to its canonical original task description.

    This mapping covers four linguistic variation levels for each of the 10
    LIBERO-goal tasks:
      - DEFAULT : The exact command used in standard training/evaluation
      - L1      : Lexical paraphrase (synonym substitution or minor rephrasing)
      - L2      : Passive voice or descriptive reformulation
      - L3      : Indirect referential expression identifying objects by context

    The function also includes known alternate default formulations (e.g.,
    "put the wine bottle on the top of the cabinet" → Task 3) to handle
    minor inconsistencies in how BDDL files phrase the same task.

    All dictionary keys are lowercased before returning, enabling
    case-insensitive lookup from parsed log file strings.

    Returns
    -------
    dict
        A mapping from lowercased variation string (str) → canonical task
        description string (str). Example:
          {
            "put the bowl on the stove"       : "Put the bowl on the stove",
            "set the bowl on the stove"       : "Put the bowl on the stove",
            "the stove needs to have ..."     : "Put the bowl on the stove",
            ...
          }

    Notes
    -----
    - Keys are converted to lowercase so that log-file strings, which may
      differ in capitalization, can be matched reliably.
    - Adding a new variation only requires inserting a new entry into
      `raw_mapping` before the final lowercase conversion.
    """
    # raw_mapping: all keys are in their original mixed-case form for readability.
    # They will be converted to lowercase at the end of this function.
    raw_mapping = {}

    # ── Task 1: Open the middle layer of the drawer ───────────────────────
    orig_1 = "Open the middle layer of the drawer"
    raw_mapping["open the middle layer of the drawer"] = orig_1          # DEFAULT
    raw_mapping["Pull the middle layer of the drawer"] = orig_1          # L1: verb swap (open → pull)
    raw_mapping["The middle layer of the drawer needs to be opened"] = orig_1   # L2: passive
    raw_mapping["Open the layer of the drawer located between the top and bottom"] = orig_1  # L3: referential

    # ── Task 2: Put the bowl on the stove ─────────────────────────────────
    orig_2 = "Put the bowl on the stove"
    raw_mapping["put the bowl on the stove"] = orig_2                    # DEFAULT
    raw_mapping["Set the bowl on the stove"] = orig_2                    # L1: verb swap (put → set)
    raw_mapping["The stove needs to have the bowl on it"] = orig_2       # L2: passive/descriptive
    raw_mapping["Put the object between the wine bottle and the cream cheese on the stove"] = orig_2  # L3: indirect reference

    # ── Task 3: Put the wine bottle on the top of the drawer ─────────────
    orig_3 = "Put the wine bottle on the top of the drawer"
    raw_mapping["put the wine bottle on top of the drawer"] = orig_3         # DEFAULT (no "the")
    raw_mapping["put the wine bottle on the top of the cabinet"] = orig_3    # Alternate default (cabinet vs drawer)
    raw_mapping["Place the wine bottle on the top of the cabinet"] = orig_3  # L1: verb swap (put → place)
    raw_mapping["Top of the cabinet needs to have the wine bottle on it"] = orig_3  # L2: passive
    raw_mapping["Put the object behind the bowl on the top of the cabinet"] = orig_3  # L3: indirect reference

    # ── Task 4: Open the top layer of the drawer and put the bowl inside ──
    orig_4 = "Open the top layer of the drawer and put the bowl inside"
    raw_mapping["Open the top drawer and put the bowl inside"] = orig_4   # DEFAULT (abbreviated)
    raw_mapping["Open the top layer of the drawer and put the bowl inside"] = orig_4  # Alternate default (full)
    raw_mapping["Pull the top layer of the drawer and place the bowl inside"] = orig_4  # L1: pull+place
    raw_mapping["Pull the top layer of the drawer and put the bowl inside"] = orig_4   # L1 alt: pull only
    raw_mapping["The top layer of the drawer needs to be opened and the bowl needs to be put inside"] = orig_4  # L2: passive
    raw_mapping["Open the top layer of the drawer and put the object between the plate and the cream cheese inside"] = orig_4  # L3: indirect

    # ── Task 5: Put the bowl on the top of the drawer ─────────────────────
    orig_5 = "Put the bowl on the top of the drawer"
    raw_mapping["Put the bowl on top of the drawer"] = orig_5              # DEFAULT (no "the")
    raw_mapping["put the bowl on the top of the cabinet"] = orig_5         # Alternate default (cabinet)
    raw_mapping["Place the bowl on the top of the cabinet"] = orig_5       # L1: verb swap
    raw_mapping["The top of the cabinet needs to have the bowl on it"] = orig_5  # L2: passive
    raw_mapping["Put the object between the wine bottle and the cream cheese on the top of the cabinet"] = orig_5  # L3: indirect

    # ── Task 6: Push the plate to the front of the stove ──────────────────
    orig_6 = "Push the plate to the front of the stove"
    raw_mapping["push the plate to the front of the stove"] = orig_6       # DEFAULT
    raw_mapping["Move the plate to the front of the stove"] = orig_6       # L1: verb swap (push → move)
    raw_mapping["The space in front of the stove needs to have the plate in it"] = orig_6  # L2: descriptive
    raw_mapping["Push the object in front of the drawer to the front of the stove"] = orig_6  # L3: indirect

    # ── Task 7: Put the cream cheese in the bowl ──────────────────────────
    orig_7 = "Put the cream cheese in the bowl"
    raw_mapping["Put the cream cheese in the bowl"] = orig_7               # DEFAULT
    raw_mapping["put the cream cheese on the bowl"] = orig_7               # Alternate default (on vs in)
    raw_mapping["Place the cream cheese on the bowl"] = orig_7             # L1: verb swap + "on"
    raw_mapping["Place the cream cheese in the bowl"] = orig_7             # L1 alt: verb swap + "in"
    raw_mapping["The cream cheese needs to be put on the bowl"] = orig_7   # L2: passive
    raw_mapping["Put the object in front of the stove on the bowl"] = orig_7  # L3: indirect reference

    # ── Task 8: Turn on the stove ─────────────────────────────────────────
    orig_8 = "Turn on the stove"
    raw_mapping["turn on the stove"] = orig_8                              # DEFAULT
    raw_mapping["Switch on the stove"] = orig_8                            # L1: verb swap (turn → switch)
    raw_mapping["The stove needs to be turned on"] = orig_8                # L2: passive
    raw_mapping["Turn on the object behind the cream cheese"] = orig_8     # L3: indirect reference

    # ── Task 9: Put the bowl on the plate ─────────────────────────────────
    orig_9 = "Put the bowl on the plate"
    raw_mapping["put the bowl on the plate"] = orig_9                      # DEFAULT
    raw_mapping["Place the bowl on the plate"] = orig_9                    # L1: verb swap
    raw_mapping["The plate needs to have the bowl on it"] = orig_9         # L2: passive
    raw_mapping["Put the object between the wine bottle and the cream cheese on the plate"] = orig_9  # L3: indirect

    # ── Task 10: Put the wine bottle on the rack ──────────────────────────
    orig_10 = "Put the wine bottle on the rack"
    raw_mapping["put the wine bottle on the rack"] = orig_10               # DEFAULT
    raw_mapping["Place the wine bottle on the rack"] = orig_10             # L1: verb swap
    raw_mapping["The rack needs to be filled with the wine bottle in it"] = orig_10  # L2: descriptive
    raw_mapping["Put the object behind the bowl on the rack"] = orig_10    # L3: indirect reference

    # Convert all keys to lowercase to enable case-insensitive matching
    # when comparing against task strings extracted from log files
    mapping = {k.lower(): v for k, v in raw_mapping.items()}

    return mapping


# =========================
# PARSING TXT FILES
# =========================


def parse_txt_file(filepath):
    """
    Parse a single TinyVLA evaluation log file and extract per-task success rates.

    The expected log file format uses the following marker lines:
      - "Original Command: <task_description>"
        or "Variation Command: <task_description>"
          → marks the start of a task block and sets `current_task`
      - "# episodes: <N>"
          → records the total number of episodes run for this task
      - "Task success rate: <X.XXXX>"
          → records the decimal success rate; converted to percentage

    Each task block is delimited by the "Task success rate:" line, which also
    resets the parser state (`current_task` and `current_episodes`).

    Parameters
    ----------
    filepath : str
        Absolute or relative path to the `.txt` log file to parse.

    Returns
    -------
    rates : dict
        Mapping from task_description (str) → success rate in percent (float).
        Example: {"Put the bowl on the stove": 84.0}
    episodes : dict
        Mapping from task_description (str) → number of episodes run (int).
        Defaults to 50 if the "# episodes:" line was not found.
    task_order : list of str
        Task description strings in the order they first appear in the file.
        Used to preserve log file ordering when merging across files.

    Notes
    -----
    - Duplicate task entries (same `current_task` appearing more than once)
      are silently ignored; only the first occurrence is retained. This
      prevents double-counting when logs contain repeated summary blocks.
    - The success rate is read as a decimal (e.g., 0.8400) and multiplied
      by 100 to convert to a percentage (84.0%) for display.
    - Regex patterns are used for robust extraction of numeric values even
      if surrounding text varies slightly between log versions.
    """
    rates = {}         # task → success rate (%)
    episodes = {}      # task → episode count
    task_order = []    # ordered list of task descriptions encountered

    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    current_task = None      # Tracks the active task block being parsed
    current_episodes = None  # Tracks the episode count for the current task block

    for i, line in enumerate(lines):
        line = line.strip()  # Remove leading/trailing whitespace and newline characters

        # ── Detect task command markers ────────────────────────────────────
        # "Original Command:" marks the start of a default/training-distribution task block
        if "Original Command:" in line:
            current_task = line.split("Original Command:")[-1].strip()
        # "Variation Command:" marks the start of a linguistic variation task block
        elif "Variation Command:" in line:
            current_task = line.split("Variation Command:")[-1].strip()

        # ── Extract episode count ──────────────────────────────────────────
        # Match "# episodes: N" to record how many trials were run for this task
        if current_task and "# episodes:" in line:
            match = re.search(r'# episodes:\s*(\d+)', line)
            if match:
                current_episodes = int(match.group(1))  # Convert captured string to integer

        # ── Extract success rate and finalize task block ───────────────────
        # "Task success rate: X.XXXX" marks the end of a task block
        if current_task and "Task success rate:" in line:
            match = re.search(r'Task success rate:\s*([\d.]+)', line)
            if match:
                # Convert decimal rate to percentage (e.g., 0.8400 → 84.0)
                rate_value = float(match.group(1)) * 100

                if current_task not in rates:  # Skip duplicates (keep first occurrence only)
                    rates[current_task] = rate_value
                    # Use parsed episode count, or fall back to 50 (standard LIBERO default)
                    episodes[current_task] = current_episodes if current_episodes else 50
                    task_order.append(current_task)

                # Reset parser state for the next task block
                current_task = None
                current_episodes = None

    return rates, episodes, task_order


def merge_txt_files(txt_files_list):
    """
    Merge multiple TinyVLA log files belonging to the same random seed.

    When a single evaluation run is split across multiple log files (e.g.,
    different task groups run in separate jobs), this function aggregates
    all results. If the same task appears in multiple files, its success rates
    are averaged (arithmetic mean).

    Parameters
    ----------
    txt_files_list : list of str
        List of file paths to `.txt` log files for a single seed. May contain
        one or more files.

    Returns
    -------
    merged_rates : dict
        Mapping from task_description (str) → averaged success rate in % (float).
        If a task appears in N files, the reported rate is the mean of N values.
    task_episodes : dict
        Mapping from task_description (str) → episode count (int).
        Always set to 50, since LIBERO evaluations use 50 trials per task.
    all_tasks : list of str
        Task descriptions in the order they were first encountered across
        all merged files. Preserves cross-file ordering.

    Notes
    -----
    - The defaultdict(list) allows appending multiple success rate values
      for the same task without initialization.
    - Episode count is hardcoded to 50 per task, matching the LIBERO standard.
      This is intentional: averaging partial episode counts would be misleading.
    """
    from collections import defaultdict

    # Maps task_description → list of success rate values (one per file where it appears)
    task_rates_list = defaultdict(list)
    task_episodes = {}    # task → episode count (always 50)
    all_tasks = []        # Ordered list of unique task descriptions seen across all files

    for filepath in txt_files_list:
        # Parse each file and accumulate results
        rates, episodes, task_order = parse_txt_file(filepath)

        for task in task_order:
            if task not in task_rates_list:
                all_tasks.append(task)  # First time seeing this task: add to ordered list
            task_rates_list[task].append(rates[task])  # Append this file's rate to the list
            task_episodes[task] = 50  # Hardcode episode count to LIBERO standard (50 per task)

    # Compute per-task arithmetic mean across all files that reported it
    merged_rates = {}
    for task, rates_list in task_rates_list.items():
        merged_rates[task] = sum(rates_list) / len(rates_list)  # Arithmetic mean

    return merged_rates, task_episodes, all_tasks


# =========================
# EXCEL GENERATION
# =========================


def write_excel_comparison(output_xlsx, txt_files_by_seed):
    """
    Parse all seed log files, aggregate results, and write the formatted Excel table.

    This is the main reporting function. It orchestrates the full pipeline:
      1. Parse and merge log files for each of the 3 seeds.
      2. Map every variation command to its canonical original task description.
      3. Iterate over the fixed canonical task order.
      4. For each task and seed, extract success rate and compute N/50 completion.
      5. Compute per-task mean ± sample std across seeds.
      6. Append a final summary row with per-seed and global mean ± std.
      7. Auto-adjust column widths and save the workbook.

    Parameters
    ----------
    output_xlsx : str
        Output file path for the generated Excel workbook (e.g., "results.xlsx").
    txt_files_by_seed : dict
        Dictionary mapping seed index (int: 0, 1, 2) → list of file path strings.
        Example:
          {
            0: ["logs/seed0_tasks1-5.txt", "logs/seed0_tasks6-10.txt"],
            1: ["logs/seed1_all.txt"],
            2: ["logs/seed2_all.txt"]
          }

    Returns
    -------
    None
        Writes the Excel file to `output_xlsx` and prints status messages.

    Notes
    -----
    Global Mean ± Std Computation (Standard VLA Convention):
    ─────────────────────────────────────────────────────────
    Rather than computing the standard deviation across all individual task×seed
    combinations, the global std is computed across the per-seed means:
      1. Compute mean_seed_k = mean(all task rates for seed k)   for k in {0,1,2}
      2. global_mean = mean(mean_seed_0, mean_seed_1, mean_seed_2)
      3. global_std  = sample_std(mean_seed_0, mean_seed_1, mean_seed_2)

    This convention matches how VLA papers report aggregate performance
    (variability across seeds, not across tasks).

    NaN Handling:
    ─────────────
    If a task is missing from a seed's log files, its rate is set to float('nan').
    NaN values are excluded from mean/std computations. The completion cell
    defaults to "0/50" for missing tasks.
    """
    # ── Step 1: Parse and merge all log files per seed ─────────────────────
    all_rates = []      # List of 3 dicts: all_rates[seed_idx][task] = rate (%)
    all_episodes = []   # List of 3 dicts: all_episodes[seed_idx][task] = episode_count
    task_order = None   # Will be set from the first seed's task order

    print("\n[INFO] Parsing e merge dei file txt...")
    for seed_idx in range(3):
        filepaths = txt_files_by_seed[seed_idx]
        print(f"  - Seed {seed_idx}: {len(filepaths)} file")
        for fp in filepaths:
            print(f"    • {os.path.basename(fp)}")  # Print filename only (not full path)

        # Merge all files for this seed into a single rates dict
        rates, episodes, order = merge_txt_files(filepaths)
        all_rates.append(rates)
        all_episodes.append(episodes)

        # Use the first seed's task order as the reference order
        if task_order is None:
            task_order = order

        print(f"    ✓ Trovati {len(rates)} task totali")

    # ── Step 2: Build variation → original mapping ─────────────────────────
    variation_to_original = get_variation_mapping()  # Lowercase keys → canonical task strings

    # Invert the mapping: find which variation string was actually found in the files
    # for each canonical original task. This is the string that will be displayed
    # in the "Variation Task Command" column of the Excel table.
    original_to_variation = {}
    print("\n[INFO] Identificazione variazioni nei file...")
    for task in task_order:
        task_lower = task.lower()  # Normalize to lowercase for case-insensitive lookup
        if task_lower in variation_to_original:
            orig = variation_to_original[task_lower]       # Get the canonical task name
            original_to_variation[orig] = task             # Map canonical → actual variation string
            print(f"  ✓ '{task}' → '{orig}'")
        else:
            # Task not found in mapping: treat itself as its own canonical form
            print(f"  ⚠ Non mappata: '{task}'")
            original_to_variation[task] = task  # Fallback: use the task as its own "variation"

    # ── Step 3: Use the fixed canonical task order for consistent row layout ──
    fixed_task_order = get_task_order()

    # ── Step 4: Create Excel workbook ─────────────────────────────────────
    wb = Workbook()
    ws = wb.active
    ws.title = "Comparison"  # Name the active worksheet

    # ── Step 5: Write column header row ───────────────────────────────────
    ws.append([
        "Original Task Command",
        "Variation Task Command",
        "Success Rate (%) - Seed 0",
        "Task Completion - Seed 0",
        "Success Rate (%) - Seed 1",
        "Task Completion - Seed 1",
        "Success Rate (%) - Seed 2",
        "Task Completion - Seed 2",
        "Mean Success Rate (%) ± Std",
        "Mean Task Completion"
    ])

    # Apply bold font and center+wrap alignment to all header cells
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal='center', wrap_text=True)

    # ── Step 6: Accumulators for the final summary row ─────────────────────
    # all_seed_rates[k]       : list of per-task success rates for seed k
    # all_seed_completions[k] : list of (success_count, episode_count) tuples for seed k
    all_seed_rates = [[], [], []]
    all_seed_completions = [[], [], []]

    print("\n[INFO] Generazione tabella Excel...")

    # ── Step 7: Process each canonical task in fixed order ─────────────────
    for orig_task in fixed_task_order:
        # Find the actual variation string used in the log files for this canonical task
        variation = original_to_variation.get(orig_task, orig_task)

        seed_rates = []         # Success rates (%) for this task, one per seed
        seed_completions = []   # "N/ep" strings for this task, one per seed
        seed_success_counts = []  # Integer success counts per seed
        seed_episode_counts = []  # Episode counts per seed

        # ── Extract data for each seed ─────────────────────────────────────
        for seed_idx in range(3):
            if variation in all_rates[seed_idx]:
                # Task found in this seed's data
                rate = all_rates[seed_idx][variation]             # Success rate in %
                ep = all_episodes[seed_idx][variation]             # Episode count (50)

                # Compute integer success count from rate and episode count
                success_count = int(round(rate / 100 * ep))

                seed_rates.append(rate)
                seed_completions.append(f"{success_count}/{ep}")
                seed_success_counts.append(success_count)
                seed_episode_counts.append(ep)

                # Accumulate for per-seed summary statistics
                all_seed_rates[seed_idx].append(rate)
                all_seed_completions[seed_idx].append((success_count, ep))
            else:
                # Task missing from this seed's log files: use NaN / zero placeholder
                seed_rates.append(float('nan'))
                seed_completions.append("0/50")
                seed_success_counts.append(0)
                seed_episode_counts.append(50)

        # ── Compute per-task mean ± sample std across seeds ────────────────
        # Exclude NaN values (tasks missing from some seeds)
        valid_rates = [r for r in seed_rates if r == r]  # NaN != NaN is always True, so this filters NaN

        if valid_rates:
            mean_rate = sum(valid_rates) / len(valid_rates)  # Arithmetic mean

            if len(valid_rates) > 1:
                # Sample standard deviation: divide by (N-1) for unbiased estimate
                std_rate = math.sqrt(
                    sum((r - mean_rate) ** 2 for r in valid_rates) / (len(valid_rates) - 1)
                )
            else:
                std_rate = 0.0  # Cannot compute std with a single value

            mean_std_display = f"{mean_rate:.1f}% ± {std_rate:.1f}%"
        else:
            # All seeds missing this task
            mean_rate = float('nan')
            std_rate = float('nan')
            mean_std_display = "nan%"

        # Truncate variation string if longer than 50 characters to fit Excel column
        var_display = variation if len(variation) <= 50 else variation[:47] + "..."

        # Compute mean task completion: average successes out of 50 episodes
        total_success = sum(seed_success_counts)       # Total successes across all 3 seeds
        total_episodes = sum(seed_episode_counts)      # Total episodes across all 3 seeds

        # Mean successes per seed (based on mean_rate, not raw total)
        avg_success = int(round(mean_rate / 100 * 50))  # e.g., 84.0% → 42/50
        avg_episodes = 50  # Each seed always uses exactly 50 episodes per task

        # ── Append data row to the worksheet ──────────────────────────────
        ws.append([
            orig_task,                  # Column 1: canonical original task name
            var_display,                # Column 2: variation command (truncated if needed)
            # Columns 3-4: Seed 0 — success rate and completion count
            f"{seed_rates[0]:.1f}%" if seed_rates[0] == seed_rates[0] else "nan%",
            seed_completions[0],
            # Columns 5-6: Seed 1
            f"{seed_rates[1]:.1f}%" if seed_rates[1] == seed_rates[1] else "nan%",
            seed_completions[1],
            # Columns 7-8: Seed 2
            f"{seed_rates[2]:.1f}%" if seed_rates[2] == seed_rates[2] else "nan%",
            seed_completions[2],
            mean_std_display,           # Column 9: mean ± std across seeds
            f"{avg_success}/{avg_episodes}"  # Column 10: mean completion as N/50
        ])

    # ── Step 8: Build the final summary row ───────────────────────────────
    # This row summarizes the mean ± std success rate across ALL tasks,
    # separately for each seed and globally.
    final_row = ["Mean% ± Std%", ""]  # Columns 1-2: label (no variation applicable)

    # Per-seed summary statistics
    for seed_idx in range(3):
        rates = all_seed_rates[seed_idx]  # All per-task success rates for this seed

        if rates:
            mean = sum(rates) / len(rates)  # Mean success rate across all tasks for this seed

            if len(rates) > 1:
                # Sample std across all task success rates for this seed
                std = math.sqrt(
                    sum((r - mean) ** 2 for r in rates) / (len(rates) - 1)
                )
            else:
                std = 0.0

            # Total completions: sum of successes and episodes across all tasks for this seed
            total_success = sum(c[0] for c in all_seed_completions[seed_idx])
            total_episodes = sum(c[1] for c in all_seed_completions[seed_idx])

            final_row.append(f"{mean:.2f}% ± {std:.2f}%")          # "XX.XX% ± YY.YY%"
            final_row.append(f"{total_success}/{total_episodes}")    # "N/M"
        else:
            final_row.append("N/A")   # No data for this seed
            final_row.append("0/0")

    # ── Global mean ± std (standard VLA reporting convention) ─────────────
    # Compute the mean of each seed's mean (not the pooled std across all tasks)
    seed_means = []
    for seed_idx in range(3):
        if all_seed_rates[seed_idx]:
            # Per-seed mean: average success rate across all tasks for seed k
            seed_mean = sum(all_seed_rates[seed_idx]) / len(all_seed_rates[seed_idx])
            seed_means.append(seed_mean)

    if seed_means:
        # Global mean: average of the three seed means
        global_mean = sum(seed_means) / len(seed_means)

        if len(seed_means) > 1:
            # Sample std across seed-level means (3 values: one per seed)
            # This is the standard convention in VLA papers for reporting robustness
            global_std = math.sqrt(
                sum((m - global_mean) ** 2 for m in seed_means) / (len(seed_means) - 1)
            )
        else:
            global_std = 0.0

        # Total completions across all seeds and all tasks
        global_success = sum(
            sum(c[0] for c in all_seed_completions[i]) for i in range(3)
        )
        global_episodes = sum(
            sum(c[1] for c in all_seed_completions[i]) for i in range(3)
        )

        final_row.append(f"{global_mean:.2f}% ± {global_std:.2f}%")  # Global mean ± std
        final_row.append(f"{global_success}/{global_episodes}")        # Global N/M
    else:
        final_row.append("N/A")
        final_row.append("0/0")

    ws.append(final_row)  # Append the completed final summary row

    # Apply bold formatting to the final summary row for visual prominence
    last_row = ws.max_row
    for cell in ws[last_row]:
        cell.font = Font(bold=True)

    # ── Step 9: Auto-adjust column widths ─────────────────────────────────
    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter  # Get the Excel column letter (A, B, C, ...)
        for cell in column:
            try:
                if cell.value and len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))  # Track the longest string in this column
            except:
                pass  # Skip cells that raise exceptions (e.g., merged or formula cells)

        # Set column width: content length + 2 padding, capped at 50 to prevent excessive width
        adjusted_width = min(max_length + 2, 50)
        ws.column_dimensions[column_letter].width = adjusted_width

    # ── Step 10: Save workbook to disk ────────────────────────────────────
    wb.save(output_xlsx)
    print(f"\n[OK] Excel salvato in: {output_xlsx}\n")


# =========================
# AUTO-DETECT FILES
# =========================


def find_txt_files_by_seed(base_dir, pattern_prefix="EVAL-libero_goal-tiny_vla"):
    """
    Automatically discover TinyVLA evaluation log files organized by seed index.

    Searches `base_dir` for `.txt` files whose names match the pattern:
        {pattern_prefix}*seed{0,1,2}*.txt

    This naming convention is generated automatically by the TinyVLA evaluation
    scripts, which embed the seed index in the filename. For example:
        EVAL-libero_goal-tiny_vla-2025-06-01_12-00-00--seed0--tasks1-5.txt

    Parameters
    ----------
    base_dir : str
        Directory path in which to search for log files.
    pattern_prefix : str, optional
        Filename prefix shared by all log files to search for.
        Default: "EVAL-libero_goal-tiny_vla".

    Returns
    -------
    dict or None
        Dictionary mapping seed index (int: 0, 1, 2) → sorted list of matching
        file path strings. Returns None if no files are found for any seed,
        allowing the caller to handle the error.

    Notes
    -----
    - Files within each seed are sorted alphabetically by filename, which
      typically corresponds to the task group order (e.g., tasks 1-5 before 6-10).
    - Both underscore (`_`) and hyphen (`-`) separators are supported because
      `glob` treats them as literal characters in the `*seed{N}*` wildcard.
    - If any seed has zero matching files, a warning is printed and None is
      returned immediately, preventing a partially-initialized result.

    Example
    -------
    >>> files = find_txt_files_by_seed("/logs", "EVAL-libero_goal-tiny_vla")
    >>> files[0]
    ['/logs/EVAL-libero_goal-tiny_vla-2025-06-01--seed0--part1.txt',
     '/logs/EVAL-libero_goal-tiny_vla-2025-06-01--seed0--part2.txt']
    """
    txt_files_by_seed = {0: [], 1: [], 2: []}  # Initialize empty lists for each seed

    print(f"\n[INFO] Cercando file .txt in: {base_dir}")
    print(f"Pattern: {pattern_prefix}*seed*{{0,1,2}}*.txt")

    for seed_idx in range(3):
        # Build the glob pattern: matches any file with the prefix and "seed{N}" in the name
        pattern = os.path.join(base_dir, f"{pattern_prefix}*seed{seed_idx}*.txt")
        matches = glob.glob(pattern)  # Expand the pattern to a list of matching paths

        matches.sort()  # Sort alphabetically to ensure consistent processing order

        txt_files_by_seed[seed_idx] = matches

        if matches:
            print(f"  ✓ Seed {seed_idx}: {len(matches)} file")
            for m in matches:
                print(f"    • {os.path.basename(m)}")  # Show filename only (not full path)
        else:
            # Missing files for this seed: the caller must handle this error
            print(f"  ✗ Seed {seed_idx}: nessun file trovato!")
            return None  # Return None to signal that the auto-detect failed

    return txt_files_by_seed


# =========================
# MAIN
# =========================


def main():
    """
    Command-line entry point for the TinyVLA LIBERO task comparison Excel generator.

    Parses CLI arguments, determines which log files to use (auto-detect or manual),
    and calls `write_excel_comparison` to produce the output `.xlsx` file.

    Two mutually exclusive operating modes are supported:

    **Auto-detect mode** (``--txt_dir``):
      The script searches the given directory for `.txt` files whose names match
      the pattern ``{--pattern}*seed{0,1,2}*.txt``. Files for each seed are
      collected automatically. This is the recommended mode for standard TinyVLA
      evaluation workflows.

    **Manual mode** (``--manual``):
      The user explicitly provides file lists for each seed using ``--seed0``,
      ``--seed1``, and ``--seed2``. This is useful when files do not follow the
      standard naming convention or are located in different directories.

    CLI Arguments
    -------------
    Mutually exclusive group (one is required):
      --txt_dir PATH
          Directory containing all `.txt` log files (auto-detect mode).
      --manual
          Enable manual file specification mode.

    Optional:
      --pattern PREFIX
          Filename prefix for auto-detect matching.
          Default: "EVAL-libero_goal-tiny_vla".
      --seed0 FILE [FILE ...]
          One or more log file paths for seed 0 (manual mode only).
      --seed1 FILE [FILE ...]
          One or more log file paths for seed 1 (manual mode only).
      --seed2 FILE [FILE ...]
          One or more log file paths for seed 2 (manual mode only).

    Positional:
      output_xlsx
          Path for the output Excel file (e.g., "results/comparison.xlsx").

    Exit Codes
    ----------
    0 : Success — Excel file written successfully.
    1 : Error — manual mode used without specifying all three seed file lists,
        or auto-detect failed to find files for all seeds.

    Examples
    --------
    Auto-detect:
        python generate_excel_comparison.py \\
            --txt_dir /mnt/logs \\
            --pattern EVAL-libero_goal-tiny_vla \\
            output.xlsx

    Manual (multiple files per seed):
        python generate_excel_comparison.py \\
            --manual \\
            --seed0 logs/seed0_part1.txt logs/seed0_part2.txt \\
            --seed1 logs/seed1.txt \\
            --seed2 logs/seed2.txt \\
            output.xlsx
    """
    parser = argparse.ArgumentParser(
        description="Genera tabella Excel da file txt TinyVLA (supporta file multipli per seed)"
    )

    # Mutually exclusive group: user must choose EITHER --txt_dir OR --manual (not both)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--txt_dir",
        help="Directory contenente i file .txt (auto-detect per seed)"
    )
    group.add_argument(
        "--manual",
        action="store_true",  # Flag: True if --manual is specified, False otherwise
        help="Modalità manuale: specifica file per ogni seed"
    )

    # Optional arguments for file discovery pattern and manual file lists
    parser.add_argument(
        "--pattern",
        default="EVAL-libero_goal-tiny_vla",
        help="Prefix pattern per auto-detect (default: EVAL-libero_goal-tiny_vla)"
    )
    parser.add_argument(
        "--seed0",
        nargs="+",  # Accepts one or more values: "--seed0 file1.txt file2.txt"
        help="File per seed 0 (modalità manuale)"
    )
    parser.add_argument(
        "--seed1",
        nargs="+",
        help="File per seed 1 (modalità manuale)"
    )
    parser.add_argument(
        "--seed2",
        nargs="+",
        help="File per seed 2 (modalità manuale)"
    )
    parser.add_argument(
        "output_xlsx",
        help="File Excel di output"
    )

    args = parser.parse_args()

    # Print ASCII banner to identify the script and its capabilities
    print("\n" + "=" * 60)
    print("  TINYVLA LIBERO TASK COMPARISON FROM TXT FILES")
    print("  (Supporting Multiple Files Per Seed)")
    print("=" * 60)

    # ── Determine the file-to-seed mapping based on the chosen mode ────────
    if args.manual:
        # Manual mode: all three --seedN arguments must be provided
        if not (args.seed0 and args.seed1 and args.seed2):
            print("\n[ERROR] Modalità manuale richiede --seed0, --seed1, --seed2!")
            exit(1)  # Exit with error code 1
        # Build the seed file mapping from CLI arguments
        txt_files_by_seed = {
            0: args.seed0,   # List of file paths for seed 0
            1: args.seed1,   # List of file paths for seed 1
            2: args.seed2    # List of file paths for seed 2
        }
    else:
        # Auto-detect mode: scan the directory for matching files
        txt_files_by_seed = find_txt_files_by_seed(args.txt_dir, args.pattern)
        if txt_files_by_seed is None:
            # find_txt_files_by_seed returns None if any seed has no matching files
            print("\n[ERROR] Non ho trovato file per tutti e 3 i seed!")
            exit(1)

    # ── Generate the Excel comparison table ────────────────────────────────
    write_excel_comparison(args.output_xlsx, txt_files_by_seed)

    # Print completion banner
    print("=" * 60)
    print("  COMPLETATO!")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()  # Invoke main() only when this script is executed directly (not imported)